### ISSUE TITLE
strtok 是回傳指標對吧   這樣比較會不會有問題? mystrtok("abcdedf", "ed") == strtok("abcdedf", "ed")

### ISSUE THREAD

**Issue by arthur0824hao** [Darrin-Lin/2024_NTNU_ComputerProgramming-II_TestCase#2]

**Comment by Darrin-Lin** [comment]
目前那邊還沒正式寫，目前只是先丟草稿上去。

**Comment by arthur0824hao** [comment]
case -7:
    
        printf("mystrtok\n");
        char testStr[] = "abcdedf";  
        char delim[] = "ed";         
        char *result1 = mystrtok(testStr, delim);
        char testStrStd[] = "abcdedf"; 
        char *result2 = strtok(testStrStd, delim);
        
        
        if ((result1 == NULL && result2 == NULL) ||
            (result1 != NULL && result2 != NULL && strcmp(result1, result2) == 0)) {
            printf("true\n");
        } else {
            printf("false\n");
        }
        break;

**Comment by arthur0824hao** [comment]
我另外開一個字串  然後自己測 , 過了 參考看看

**Comment by Darrin-Lin** [comment]
我開負數是直接丟字串進去，讓大家看會不會 Segmentation fault，其實裡面是什麼不重要，要測是否正確可以用 case 7。
